import {StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';

const ProfileStyle = StyleSheet.create({
  body: {
    flex: 1,
    backgroundColor: 'white',
    flexDirection: 'column',
  },
  keyboardAvoid: {
    flex: 1,
    marginTop: 20,
  },
  scrollViewKeyboard: {
    flex: 1,
    marginTop: hp('16%'),
  },
  globalMarginTop: {
    marginTop: 20,
  },
  bioMarginTop: {
    marginTop: hp('3%'),
  },
  globalFlex: {
    flex: 1,
  },
  profileImageStyle: {
    backgroundColor: 'transparent',
    width: 121,
    height: 121,
    marginTop: hp('11%'),
    borderRadius: 130 / 2,
  },
  globalFlexDirectionRow: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  enthMarginTop: {
    marginTop: hp('0%'),
  },
  profileBg: {
    backgroundColor: 'transparent',
    marginTop: 100,
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
  },
  scrollviewContainer: {
    backgroundColor: 'white',
    flexDirection: 'column',
    //margin: 20,
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 20, //marginTop: 20,
  },
  photoLayout: {
    backgroundColor: '#cc0166',
    borderRadius: 10,
    justifyContent: 'center',
    height: 90,
    width: 90,
    marginTop: 10,
  },
  userImageView: {
    height: 100,
    width: '100%',
    marginTop: 10,
    flexDirection: 'row',
  },
  logo: {
    width: wp('20%'),
    height: hp('25%'),
    padding: 10,
  },
  inputLayout: {
    flexDirection: 'row',
    backgroundColor: 'white',
    height: 45,
    borderColor: '#d6d6d6',
    borderWidth: 1,
    borderRadius: 10,
    marginBottom: 10,
    marginTop: 10,
    alignItems: 'center',
  },
  inputBioLayout: {
    flexDirection: 'row',
    backgroundColor: 'white',
    height: hp('12%'),
    borderColor: '#d6d6d6',
    borderWidth: 1,
    borderRadius: 10,
    marginTop: 10,
    alignItems: 'flex-start',
  },
  input: {
    width: wp('100%'),
    margin: 10,
    fontSize: 16,
    justifyContent: 'center',

    //fontFamily: 'Poppins-Regular',
  },
  bioInput: {
    width: wp('87%'),
    height: hp('10'),
    paddingLeft: 10,
    paddingRight: 10,
    fontSize: 12,
    textAlign: 'justify',

    //fontFamily: 'Poppins-Regular',
  },
  inputWithCalendar: {
    width: wp('80%'),
    height: 45,
    paddingLeft: 10,
    paddingRight: 10,
    fontSize: 12,
    //fontFamily: 'Poppins-Regular',
  },
  inputDob: {
    width: wp('78%'),
    fontSize: 16,
    margin: 10,
    justifyContent: 'center',
    //fontFamily: 'Poppins-Regular',
  },
  pickerDob: {
    width: wp('6%'),
    height: 45,
    paddingLeft: 10,
    fontSize: 12,
    justifyContent: 'center',
    //fontFamily: 'Poppins-Regular',
  },
  closeIdle: {
    height: 30,
    width: 30,
    alignSelf: 'center',
    opacity: 0.5,
  },
  closeActive: {
    height: 30,
    width: 30,
    alignSelf: 'center',
  },
  forgotLayout: {
    backgroundColor: 'white',
    //height: hp('30%'),
    marginTop: 20,
    flexDirection: 'column',
  },
  textForgot: {
    fontSize: 14,
    color: '#cc0166',
    alignSelf: 'flex-start',
    //fontFamily: 'Poppins-Medium',
    lineHeight: 21,
  },
  textGenratedProfile: {
    fontSize: 14,
    color: '#cc0166',
    alignSelf: 'center',
    //fontFamily: 'Poppins-Regular',
    lineHeight: 21,
    marginTop: 20,
  },
  textLookingfor: {
    fontSize: 14,
    color: '#cc0166',
    alignSelf: 'flex-start',
    //fontFamily: 'Poppins-Medium',
    lineHeight: 18,
    marginTop: 20,
  },
  loginButtonLayout: {
    flexDirection: 'column',
    backgroundColor: '#cc0166',
    height: 45,
    borderRadius: 10,
    marginTop: 20,
    justifyContent: 'center',
  },

  textLogin: {
    fontSize: 16,
    letterSpacing: 2.4,
    color: 'white',
    alignSelf: 'center',
    //fontFamily: 'Poppins-Regular',
  },
  textSkip: {
    fontSize: 16,
    letterSpacing: 2.4,
    color: 'white',
    alignSelf: 'center',
    //fontFamily: 'Poppins-Regular',
  },
  add: {
    width: 25,
    height: 25,
    //backgroundColor: 'yellow',
    alignSelf: 'center',
    padding: 10,
  },
  genderLayout: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
    width: wp('90%'),
    height: hp('4.3%'),
    borderColor: '#d6d6d6',
    borderWidth: 1,
    borderRadius: 10,
    alignSelf: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  lookingforLayout: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
    width: wp('90%'),
    height: 35,
    borderColor: '#d6d6d6',
    borderWidth: 1,
    borderRadius: 10,
    alignSelf: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  dateLayout: {
    flexDirection: 'row',
    backgroundColor: '#cc0166',
    width: wp('44.6%'),
    height: 34,
    borderBottomLeftRadius: 9,
    borderTopLeftRadius: 9,
    alignSelf: 'center',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
  },
  friendshipLayout: {
    flexDirection: 'row',
    backgroundColor: 'white',
    width: wp('44.6%'),
    height: 34,
    justifyContent: 'center',
    alignSelf: 'center',
    borderTopRightRadius: 9,
    borderBottomRightRadius: 9,
  },
  maleLayout: {
    flexDirection: 'row',
    backgroundColor: '#cc0166',
    width: wp('29.8%'),
    height: hp('4%'),
    borderBottomLeftRadius: 9,
    borderTopLeftRadius: 9,
    alignSelf: 'center',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
  },
  femaleLayout: {
    flexDirection: 'row',
    backgroundColor: 'white',
    width: wp('29.8%'),
    height: hp('4%'),
    justifyContent: 'center',
    alignSelf: 'center',
  },
  bothLayout: {
    flexDirection: 'row',
    backgroundColor: 'white',
    width: wp('29.8%'),
    height: hp('4%'),
    justifyContent: 'center',
    alignSelf: 'center',
    borderTopRightRadius: 9,
    borderBottomRightRadius: 9,
  },
  textMale: {
    fontSize: 12,
    letterSpacing: 1.2,
    color: 'white',
    alignSelf: 'center',
    //fontFamily: 'Poppins-Regular',
  },
  textFemale: {
    fontSize: 12,
    letterSpacing: 1.2,
    color: '#cc0166',
    alignSelf: 'center',
    //fontFamily: 'Poppins-Regular',
  },
  genderIcon: {
    height: 13,
    width: 13,
    marginRight: 10,
    alignSelf: 'center',
  },
  textGenratedProfileAge: {
    fontSize: 12,
    color: '#292828',
    alignSelf: 'center',
    //fontFamily: 'Poppins-Regular',
    lineHeight: 18,
  },
  signInVivaLayout: {
    flexDirection: 'column',
    width: wp('95%'),
    height: hp('8%'),
    marginTop: 40,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  musicLogo: {
    width: 18,
    height: 18,
    alignSelf: 'flex-start',
    marginLeft: -50,
    marginRight: 40,
    marginTop: 5,
  },
  spotifyLogo: {
    width: 18,
    height: 18,
    alignSelf: 'center',
    marginLeft: -50,
    marginRight: 40,
  },
  spotifyLayout: {
    height: 45,
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 40,
    backgroundColor: '#00000b',
    alignItems: 'center',
    alignContent: 'center',
    borderRadius: 10,
    marginLeft: 20,
    marginRight: 20,
  },
  musicLayout: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
  },
  genrateProfileBg: {
    width: 131,
    height: 131,
    backgroundColor: 'transparent',
    marginTop: 100,
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    flexDirection: 'row',
  },
  textMusic: {
    fontSize: 16,
    lineHeight: 25,
    letterSpacing: 1.6,
    color: 'white',
    alignSelf: 'center',
    textAlign: 'center',
    marginBottom: 5,
    //fontFamily: 'Poppins-Regular',
  },
  textSpotify: {
    fontSize: 16,
    lineHeight: 25,
    letterSpacing: 1.6,
    color: 'white',
    alignSelf: 'center',
    textAlign: 'center',
    //fontFamily: 'Poppins-Regular',
  },
  userProfileStyle: {
    borderRadius: 10,
  },
 
});

export default ProfileStyle;
