import {StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';

const LoginStyle = StyleSheet.create({
  body: {
    flex: 1,
    backgroundColor: 'white',
  },
  referralbody: {
    height: hp('95%'),
    backgroundColor: 'white',
  },
  logo: {
    width: wp('20%'),
    height: hp('25%'),
    padding: 10,
  },
  inputLayout: {
    flexDirection: 'row',
    backgroundColor: 'white',
    height: 45,
    borderColor: '#d6d6d6',
    borderWidth: 1,
    borderRadius: 10,
    marginLeft: 20,
    marginRight: 20,
    marginTop: 10,
    marginBottom: 10,
    alignItems: 'center',
  },
  input: {
    width: wp('80%'),
    height: 45,
    paddingLeft: 10,
    paddingRight: 10,
    fontSize: 12,
    //fontFamily: 'Poppins-Regular',
  },
  inputDob: {
    width: wp('72%'),
    height: 45,
    paddingLeft: 10,
    fontSize: 12,
    marginTop:30,
    justifyContent: 'center',
    //fontFamily: 'Poppins-Regular',
  },
  pickerDob: {
    width: wp('15%'),
    height: 45,
    paddingLeft: 10,
    fontSize: 12,
    justifyContent: 'center',
    //fontFamily: 'Poppins-Regular',
  },
  closeIdle: {
    height: 30,
    width: 30,
    alignSelf: 'center',
  },
  genderIcon: {
    height: 15,
    width: 15,
    marginRight: 10,
    alignSelf: 'center',
  },
  femaleIcon: {
    height: 15,
    width: 22,
    marginRight: 10,
    alignSelf: 'center',
  },
  closeActive: {
    height: 30,
    width: 30,
    alignSelf: 'center',
  },
  forgotLayout: {
    height: hp('4%'),
    width: '100%'
  },
  textForgot: {
    fontSize: 12,
    marginTop: 10,
    color: '#cc0166',
    alignSelf: 'flex-end',
    //fontFamily: 'Poppins-Regular',
    lineHeight: 18,
  },
  loginButtonLayout: {
    flexDirection: 'column',
    backgroundColor: '#cc0166',
    height: 45,
    borderRadius: 10,
    margin: 20,
    justifyContent: 'center',
  },
  saveButtonLayout: {
    flexDirection: 'column',
    backgroundColor: '#cc0166',
    height: 45,
    borderRadius: 10,
    margin: 20,
    marginTop: hp('5%'),
    justifyContent: 'center',
  },
  signUpButtonLayout: {
    flexDirection: 'column',
    backgroundColor: '#cc0166',
    height: 45,
    borderRadius: 10,
    margin: 20,
    justifyContent: 'center',
  },
  textLogin: {
    fontSize: 16,
    letterSpacing: 2.4,
    color: 'white',
    alignSelf: 'center',
    //fontFamily: 'Poppins-Regular',
  },
  textMale: {
    fontSize: 12,
    letterSpacing: 1.2,
    lineHeight: 18,
    color: 'white',
    alignSelf: 'center',
    //fontFamily: 'Poppins-Regular',
  },
  facebookButtonLayout: {
    flexDirection: 'column',
    backgroundColor: '#3b4db3',
    height: 45,
    borderRadius: 10,
    marginLeft: 20,
    marginRight: 20,
    marginTop: 10,
    justifyContent: 'center',
    //fontFamily: 'Poppins-Regular',
  },
  textFacebook: {
    fontSize: 16,
    letterSpacing: 2.4,
    color: 'white',
    alignSelf: 'center',
  },
  registerLayout: {
    backgroundColor: 'white',
    flexDirection: 'row',
    height: hp('4%'),
    margin: 30,
    justifyContent: 'center',
  },
  textregister: {
    fontSize: 13,
    color: '#cc0166',
    lineHeight: 18,
    //fontFamily: 'Poppins-Regular',
  },
  textHaveAccount: {
    fontSize: 12,
    color: '#898a8f',
    lineHeight: 18,
    marginRight: 5,
    //fontFamily: 'Poppins-Regular',
  },
  dateofBirthLayout: {
    flexDirection: 'row',
    backgroundColor: 'white',
    height: hp('6%'),
    borderColor: '#d6d6d6',
    borderWidth: 1,
    borderRadius: 10,
    margin: 20,
  },
  forgotPasswordLayout: {
    backgroundColor: 'white',
    height: hp('7%'),
    marginBottom: 10,
    marginLeft: 5,
  },
  changePasswordLayout: {
    width: wp('90%'),
    height: hp('4.5%'),
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    //marginBottom: 20,
    marginLeft: 5,
  },
  textForgotLable: {
    height: hp('10%'),
    fontSize: 14,
    color: '#cc0166',
    lineHeight: 25,
    margin: 20,
    //fontFamily: 'Poppins-Regular',
  },
  textReferralCodeLable: {
    height: hp('10%'),
    fontSize: 14,
    color: '#cc0166',
    lineHeight: 25,
    textAlign: 'center',
    marginTop: 10,
    //fontFamily: 'Poppins-Regular',
  },
  textReferralOrLable: {
    height: hp('4%'),
    fontSize: 14,
    color: '#cc0166',
    lineHeight: 25,
    textAlign: 'center',
    margin: 20,
    //fontFamily: 'Poppins-Regular',
  },
  textChangePasswLable: {
    //height: hp('10%'),
    fontSize: 18,
    color: 'white',
    lineHeight: 25,
    //margin: 20,
    textAlign: 'center',
    //fontFamily: 'Poppins-Regular',
  },
  genderLayout: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
    width: wp('90%'),
    height: 45,
    borderColor: '#d6d6d6',
    borderWidth: 1,
    borderRadius: 10,
    alignSelf: 'center',
    justifyContent: 'center',
    marginTop: 10,
    marginBottom: 10,
  },
  maleLayout: {
    flexDirection: 'row',
    backgroundColor: '#cc0166',
    width: wp('44.7%'),
    height: 44,
    borderBottomLeftRadius: 9,
    borderTopLeftRadius: 9,
    alignSelf: 'center',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
  },
  femaleLayout: {
    flexDirection: 'row',
    backgroundColor: 'white',
    width: wp('44.6%'),
    height: 44,
    justifyContent: 'center',
    alignSelf: 'center',
    borderTopRightRadius: 9,
    borderBottomRightRadius: 9,
  },
  textFemale: {
    fontSize: 12,
    letterSpacing: 1.2,
    lineHeight: 18,
    color: '#cc0166',
    alignSelf: 'center',
    //fontFamily: 'Poppins-Regular',
  },
  inputForgotLayout: {
    flexDirection: 'row',
    backgroundColor: 'white',
    height: 45,
    borderColor: '#d6d6d6',
    borderWidth: 1,
    borderRadius: 10,
    marginLeft: 20,
    marginRight: 20,
    marginTop: 30,
    marginBottom: 10,
    alignItems: 'center',
  },
  inputChangeLayout: {
    flexDirection: 'row',
    backgroundColor: 'white',
    height: 45,
    borderColor: '#d6d6d6',
    borderWidth: 1,
    borderRadius: 10,
    marginLeft: 20,
    marginRight: 20,
    marginTop: 10,
    marginBottom: 10,
    alignItems: 'center',
  },
  inputForgot: {
    width: wp('79%'),
    height: 45,
    paddingLeft: 10,
    paddingRight: 10,
    fontSize: 12,
  },
  inputReferralMainLayout: {
    flexDirection: 'row',
    backgroundColor: 'white',
    height: 45,
    borderColor: '#d6d6d6',
    borderWidth: 1,
    borderRadius: 10,
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 10,
    alignItems: 'center',
  },
  inputReferralLayout: {
    flexDirection: 'row',
    backgroundColor: 'white',
    height: 45,
    //borderColor: '#d6d6d6',
    //borderWidth: 1,
    //borderRadius: 10,
    marginLeft: 20,
    marginRight: 20,
    //marginTop: 30,
    marginBottom: 10,
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  lineReferral: {
    height: 1,
    width: wp('35%'),
    backgroundColor: '#d6d6d6',
  },
});

export default LoginStyle;
